const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGGUEGA_APP: "CHANGE_LANGGUEGA_APP",
  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  //admin: gender
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIDLED: "FETCH_GENDER_FAIDLED",
  //admin: position
  FETCH_POSITION_START: "FETCH_POSITION_START",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAIDLED: "FETCH_POSITION_FAIDLED",
  //admin: ROLE
  FETCH_ROLE_START: "FETCH_ROLE_START",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIDLED: "FETCH_ROLE_FAIDLED",
  //create new user
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIDLED: "CREATE_USER_FAIDLED",
  //get all users
  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAIDLED: "FETCH_ALL_USER_FAIDLED",
  //delete users
  FETCH_DELETE_USER_SUCCESS: "FETCH_DELETE_USER_SUCCESS",
  FETCH_DELETE_USER_FAIDLED: "FETCH_DELETE_USER_FAIDLED",
  //edit users
  FETCH_EDIT_USER_SUCCESS: "FETCH_EDIT_USER_SUCCESS",
  FETCH_EDIT_USER_FAIDLED: "FETCH_EDIT_USER_FAIDLED",
});

export default actionTypes;
